// Distribution and modification of this code is not allowed and will be punish according to law in violation of intellectual property
var matchedInput = [
    "who own you|who creat you|who made you",
    "who founder|who create webplix|who own webplix|weplix founder|webplix creat|webplix ceo|ceo webplix|founder webplix",
    "khian victory|khian calderon",
    "mail",
    "fb page|facebook page|official page",
    "technical support",
    "domain free|free domain",

    "web kind|kind web|which web|web which",
    "kind question|question kind",
    "comany hour|hour company|business hour|hour business|when avail|when can i",
    "where lucena|lucena locat|locat lucena",
    "business detail|detail business|how you work|how webplix work",
    "what you offer",
    "custom design|templates",
    "pay how|how pay|pay method|debit card|credit card|paypal|gcash",
    "avail international|world wide",

    "who he|who she|who they|who them",
    "who khian",
    "offers webplix|webplix offers",
    "why choose you|why should i you|what set webplix apart|why choose webplix|why shoud i webplix|what differe webplix|what differe you|webplix offer|offer webplix",
    "fee to pay|fees|dif fee|what to pay",
    "web timeline|timeline web|how long web|web how long",
    
    "how are you|you ok",
    "can you help",
    "copyright notice",
    "web mobile friendly|web phone friendly|web responsive|responsive web|friendly mobile|friendly phone",
    "client update web own|client update own web|client web update own|client web own update|client own update web|client own web update|update client web own|update client own web|update web client own|update web own client|update own client web|update own web client|web client update own|web client own update|web update client own|web update own client|web own client update|web own update client|own client update web|own client web update|own update client web|own update web client|own web client update|own web update client",
    "web security|security web",
    "what are you|who are you",

    "web ample|ample web",
    "how much|cost",
    "what process|how develop|how website|how work",
    "how inquire|inquire how",
    "how contact inquiries|how contac support",
    "service offer|feature offer|feature service",
    "faq|what ask|what question|which ask",
    "location|where you locate",
    "about us|contac us",
    "privacy policy",

    "can you|what is|who are|where is|when is",
    "additional service|more service|other service",
    "next step|web project|after web then",
    "do you know|who s",
    "maintenance|maintaining",
    "complain",
    "name|i'm|i am",
    "feedback|recommend|suggestion|improvement",

    "webplix",
    "wow|amazing|amaze|speechless|fantastic",
    "good night",
    "hello|hi|good morning|good afternoon|good evening",
    "help",
    "ok|thank|yes|yep|yeah",
    "no|don t|did n t|does n t",
    "really|why|where|who|what|when|how",
];